# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'QuickNovel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuickNovel
  pod 'SwiftSoup', '~> 2.6.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
    end
  end
  
  # Fix for unbound variable error in Pods-QuickNovel-frameworks.sh
  # The script fails when trying to source an unset variable
  # Solution: Add 'set +u' near the top to disable unbound variable checking
  # GitHub Issue: https://github.com/CocoaPods/CocoaPods/issues/11402
  
  Dir.glob('Pods/Target Support Files/Pods-*/Pods-*-frameworks.sh').each do |frameworks_script_path|
    script_content = File.read(frameworks_script_path)
    
    # Check if we've already patched this script
    next if script_content.include?('set +u  # Allow unbound variables')
    
    # Add 'set +u' after the shebang line
    lines = script_content.split("\n")
    new_lines = []
    modified = false
    
    lines.each_with_index do |line, index|
      new_lines << line
      # Insert 'set +u' right after the shebang (#!/bin/sh or #!/usr/bin/env bash)
      if index == 0 && line.start_with?('#!')
        new_lines << 'set +u  # Allow unbound variables (fix for CocoaPods issue)'
        modified = true
      end
    end
    
    if modified
      File.write(frameworks_script_path, new_lines.join("\n"))
      puts "✓ Patched #{File.basename(frameworks_script_path)} to handle unbound variables"
    end
  end
end
